### PR TITLE
Make CastXML the default instead of GccXML (master)

### PR DESCRIPTION
**Pull request by MatthijsBurgh**
master version of #133.

As discussed in #132.

I would  prefer that these changes would also end up in `toolchain-2.9`.

### CODE REVIEW

**Comment by MatthijsBurgh** [comment]
@doudou

**Comment by g-arjones** [comment]
Would you please review the manifest file? Dependencies are missing there and the `<export>` tag seem like legacy code from the old `rosbuild` days which, AFAIK, is not supported anymore (@doudou @meyerj ?)

**Comment by MatthijsBurgh** [comment]
The commit that changed the manifest file is a commit of @meyerj which is taken from the `toolchain-2.9` branch.

**Comment by 2maz** [comment]
ruby-backports is defined in the rock.core package set, but not in orocos.toolchain package_set

**Comment by doudou** [comment]
> Would you please review the manifest file?

It is virtually unchanged from master, which is what Rock is using already.

> Dependencies are missing there 

Which ?

**Comment by g-arjones** [comment]
> It is virtually unchanged from master, which is what Rock is using already.

Yep, just saw a commit that changed it and thought it would be good to take the opportunity to review other parts of it.

> Which ?

castxml? I also see that `ruby-dev` and `ruby-backports` are in the package.xml and since typelib has ruby bindings maybe it would be good to have at least `ruby-dev` in the manifest.xml as well?

**Comment by MatthijsBurgh** [comment]
To me it rises the question, what is the difference between the `master` and the `toolchain-2.9` branch

**Comment by MatthijsBurgh** [comment]
ping ;)

**Comment by doudou** [comment]
> castxml? I also see that ruby-dev and ruby-backports are in the package.xml and since typelib has ruby bindings maybe it would be good to have at least ruby-dev in the manifest.xml as well?

'castxml' in Rock is automatically added by the rock.core package set if castxml is the selected parser. Since it disabling an optional dependency means excluding the package, this was the best solution under the circumstances.

Ack on 'ruby-backports' and 'ruby-dev'

Now, basically, these changes come from toolchain-2.9 (i.e. it's not this PR's author). I don't think we should be blocking his PR because of them.

**Comment by doudou** [comment]
> To me it rises the question, what is the difference between the master and the toolchain-2.9 branch

I don't know. The orocos and rock developments essentially happen in parallel without much synchronization (instead of "hand in hand"), so that would have to be answered by the orocos developers.

**Comment by g-arjones** [comment]
> I don't think we should be blocking his PR because of them

Fair enough.

**Review by g-arjones — APPROVED** [review]

**Review by 2maz — APPROVED** [review]

**Pull request merged**
