### PR TITLE
Fixes for the Boost version in Ubuntu 20.04

### PR DESCRIPTION
**Pull request by doudou**

### CODE REVIEW

**Comment by doudou** [comment]
I honestly don't know if it still compiles/works under 18.04. Waiting for confirmation in CI.

**Comment by g-arjones** [comment]
> don't know if it still compiles/works under 18.04

:fearful:

**Comment by doudou** [comment]
> don't know if it still compiles/works under 18.04

Well.
- the boost::test stuff either compiles and runs or does not (test suite)
- the endian stuff is not allowed to fall through anymore (it was before), so if it compiles, it should work. Plus there are tests that will fail on bad endianness detection.

So, if CI passes I'm reasonably confident it's going to be OK. I'm happy to leave it here for a while for others to put in their systems and try out.

**Comment by doudou** [comment]
And our embedded systems do run 18.04. So I'll know sooner or later :P

**Comment by g-arjones** [comment]
Yeah, I'm pretty confident that it will build and work or just break on build. Let me know once you're done so I can run tests here as well before you merge.

**Comment by doudou** [comment]
CI's passing.

**Comment by meyerj** [comment]
This patch broke the [orocos_toolchain build on Travis](https://travis-ci.com/github/orocos-toolchain/orocos_toolchain/builds/201521232), since the submodules were updated in https://github.com/orocos-toolchain/orocos_toolchain/commit/894d8f5d804268bf07a01df1775629e9cf509068, which are still running in 16.04 Xenial:
```
[ 82%] Building CXX object test/CMakeFiles/typelib_testsuite.dir/test_display.o
/home/travis/build/orocos-toolchain/orocos_toolchain/typelib/test/test_display.cc:2:58: fatal error: boost/test/tools/floating_point_comparison.hpp: No such file or directory
compilation terminated.
test/CMakeFiles/typelib_testsuite.dir/build.make:101: recipe for target 'test/CMakeFiles/typelib_testsuite.dir/test_display.o' failed
```

Likely it is time to upgrade to Bionic or Focal, but it would also be simple to still support older Boost versions, if there is no other reason why typelib depends on 18.04 or newer anyway.

See https://github.com/orocos-toolchain/rtt/commit/7aa7bbb7e8a8096221c37317a1a02641b059308c (https://github.com/orocos-toolchain/rtt/pull/317) for an example. Or do you prefer that I revert the submodule to an older version and drop support for Xenial and Boost 1.58 on branch `master`?

The macOS builds of `orocos_toolchain` are currently broken for another reason.

**Pull request merged**
