### PR TITLE
Make CastXML the default instead of GccXML

### PR DESCRIPTION
**Pull request by MatthijsBurgh**
As discussed in #132 

I don't know if this also should be merged into master.

### CODE REVIEW

**Comment by MatthijsBurgh** [comment]
@doudou

**Comment by doudou** [comment]
Looks good. I'm not in charge of the orocos-toolchain branches ... could you either change this PR merge base to master or create a new PR ? I'd like to have the review of other rock developers.

**Comment by MatthijsBurgh** [comment]
Who in maintainer of the toolchain branches? I would like this change in the `toolchain-2.9` branch.

**Comment by meyerj** [comment]
> Who in maintainer of the toolchain branches? I would like this change in the `toolchain-2.9` branch.

I tried to keep them up-to-date in the past, but without actually using typelib (or [orogen](https://github.com/orocos-toolchain/orogen)) myself in the last years. I also do not know about gccxml vs. castxml.

Ideally the extra branches would not even be needed. The only non-trivial differences are in [`manifest.xml`](https://github.com/orocos-toolchain/typelib/compare/master...toolchain-2.9#diff-06e6215f32570c3a47a6a5336751fce3691dec5f07093b0f5214a65e07a49a1e) and [`package.xml`](https://github.com/orocos-toolchain/typelib/compare/master...toolchain-2.9#diff-37a67ff78eb7260214b323353263b9af40a2fa98719a1e81937fae0159df87a3), and related to the old problem that the same filename is used by [AutoProj](https://www.rock-robotics.org/documentation/autoproj/index.html) and ROS tools like [rosdep](https://wiki.ros.org/rosdep). The latter still prefers `manifest.xml` (dry) over `package.xml` (wet) if it exists, and handles `<depend package="...">` (other ROS packages) and `<rosdep name="...">` (packages provided via apt, pip, gems etc.) differently. That is unfortunate, the author of the package should not have to care and it depends on the build environment, which is probably why the difference has been removed for `package.xml` in [REP-0127](https://www.ros.org/reps/rep-0127.html) (latest specification is [REP-0149](https://ros.org/reps/rep-0149.html)). Additionally, AutoProj introduced useful new features like `<depend_optional>`, but which are not understood by ROS tools and cause errors. And last but not least, all the keys need to be either packages with a `package.xml` file that can be added to the workspace and built from source, or listed in the rosdep database maintained at https://github.com/ros/rosdistro/tree/master/rosdep.

So overall some coordination is required for every dependency update, to not break the build for either AutoProj or for ROS/catkin users.

The version numbers are indeed not so important, especially when building from source. But the version has to be increased for each new release into ROS - provided that this is still desirable. The last release of typelib was [into ROS indigo back in 2015](http://repositories.ros.org/status_page/compare_indigo_kinetic_lunar_melodic.html?q=typelib) ([orocos-gbp/typelib-release](https://github.com/orocos-gbp/typelib-release)). In any case the version numbers and release cycles should IMHO not be coupled to [RTT](https://github.com/orocos-toolchain/rtt) or [Orocos Toolchain](https://github.com/orocos-toolchain/orocos_toolchain) anymore (and hence no `toolchain-2.x` branches). So please choose whatever you prefer for typelib and other packages you maintain (https://github.com/orocos-toolchain/orogen/pull/140#issuecomment-655501107).

Other changes ([master...toolchain-2.9](https://github.com/orocos-toolchain/typelib/compare/master...toolchain-2.9)) are actually trivial and could be either reverted or applied to the `master` branch?
- install `package.xml` in `CMakeLists.txt` and update the outdated maintainer email address `orocos-dev@lists.mech.kuleuven.be` (replaced by `orocos-dev@orocos.org`, which currently forwards to [orocosdev@ls.kuleuven.be](https://ls.kuleuven.be/cgi-bin/wa?A0=OROCOSDEV))
- rosbuild `Makefile` is obsolete and has been removed (https://github.com/orocos-toolchain/typelib/commit/5e8b7c8d2459bcee5f393d3039b8ae0ee7458716)
- fixes needed for linking to pthread and `Boost_THREAD_LIBRARIES` (https://github.com/orocos-toolchain/typelib/commit/40cd3a89efb4307db59324e8aabf8b7bc498bdf7)?
- some arch detection patch required for macOS back then, likely obsolete (https://github.com/orocos-toolchain/typelib/commit/6339de6629fa2c371c7f8a59fed7e17d71e2d558)?

See also https://github.com/orocos-toolchain/orogen/pull/140 and https://github.com/orocos-toolchain/rtt/pull/321. It would be very nice if we can find a solution for those kind of problems in the future, but I do not see how this can be done without deprecating `manifest.xml` in favor of `autoproj.xml` and `package.xml` (https://github.com/orocos-toolchain/rtt/pull/321#issuecomment-631755015), and keeping both up-to-date? If there is anything I can do (other than merging the two approved pull requests above), please let me know.

**Comment by MatthijsBurgh** [comment]
@meyerj thanks!

**Pull request closed without merging**
