### PR TITLE
Activation of C++11 features in castxml

### PR DESCRIPTION
**Pull request by maltewi**
Got a very simple type such as this one using C++11 features:

`MyHeader.hpp`:
```
#ifndef MYHEADER_HPP_
#define MYHEADER_HPP_

enum class MyCPP11Enum{
    VALUE = 1
};

bool my_func(MyCPP11Enum en){
    switch(en){
    case MyCPP11Enum::VALUE:
        return true;
    default:
        return false;
    }
}
#endif
```

When running `typelib` on this using `castxml` gives a warning that C++11 extensions are used for the defined Enum and also an error in the function that uses the Enum:
```
wirkus@mwirkus-lap-u:test$ typegen $PWD/bla /$PWD/MyHeader.hpp
/media/wirkus/Data/development/d-rock/install/lib/ruby/2.3.0/typelib/gccxml.rb:1039: warning: Insecure world writable dir /media/wirkus/Data/development/d-rock/base/admin_scripts/bin in PATH, mode 040777
/media/wirkus/Data/development/test/bla/types/media/wirkus/Data/development/test/bla/test/MyHeader.hpp:4:6: warning: 
      scoped enumerations are a C++11 extension [-Wc++11-extensions]
enum class MyCPP11Enum{
     ^
/media/wirkus/Data/development/test/bla/types/media/wirkus/Data/development/test/bla/test/MyHeader.hpp:10:10: warning: 
      use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
    case MyCPP11Enum::VALUE:
         ^
/media/wirkus/Data/development/test/bla/types/media/wirkus/Data/development/test/bla/test/MyHeader.hpp:10:10: error: 
      expression is not an integral constant expression
    case MyCPP11Enum::VALUE:
         ^~~~~~~~~~~~~~~~~~
2 warnings and 1 error generated.
/media/wirkus/Data/development/d-rock/install/lib/ruby/2.3.0/typelib/gccxml.rb:957:in `block (2 levels) in castxml': cannot load one of the header files /media/wirkus/Data/development/test/bla/types/media/wirkus/Data/development/test/bla/test/MyHeader.hpp: gccxml returned an error while parsing /media/wirkus/Data/development/test/bla/types/media/wirkus/Data/development/test/bla/test/MyHeader.hpp with call castxml --castxml-gccxml -x c++ -DOROCOS_TARGET=gnulinux -D__orogen2 -I/media/wirkus/Data/development/test/bla/types -I/media/wirkus/Data/development -I/media/wirkus/Data/development/test/bla/types  (ArgumentError)
	from /usr/lib/ruby/2.3.0/tempfile.rb:295:in `open'
	from /media/wirkus/Data/development/d-rock/install/lib/ruby/2.3.0/typelib/gccxml.rb:955:in `block in castxml'
	from /media/wirkus/Data/development/d-rock/install/lib/ruby/2.3.0/typelib/gccxml.rb:954:in `map'
	from /media/wirkus/Data/development/d-rock/install/lib/ruby/2.3.0/typelib/gccxml.rb:954:in `castxml'
	from /media/wirkus/Data/development/d-rock/install/lib/ruby/2.3.0/typelib/gccxml.rb:1008:in `load'
	from /media/wirkus/Data/development/d-rock/install/lib/ruby/2.3.0/typelib/gccxml.rb:1054:in `load'
	from /media/wirkus/Data/development/d-rock/install/lib/ruby/2.3.0/typelib/cxx.rb:117:in `load'
	from /media/wirkus/Data/development/d-rock/install/lib/ruby/2.3.0/typelib/registry.rb:225:in `call'
	from /media/wirkus/Data/development/d-rock/install/lib/ruby/2.3.0/typelib/registry.rb:225:in `import'
	from /media/wirkus/Data/development/d-rock/tools/orogen/lib/orogen/gen/typekit.rb:1523:in `block in perform_pending_loads'
	from /usr/lib/ruby/2.3.0/tempfile.rb:295:in `open'
	from /media/wirkus/Data/development/d-rock/tools/orogen/lib/orogen/gen/typekit.rb:1518:in `perform_pending_loads'
	from /media/wirkus/Data/development/d-rock/tools/orogen/lib/orogen/gen/typekit.rb:1952:in `generate'
	from /media/wirkus/Data/development/d-rock/tools/orogen/bin/typegen:116:in `<main>'
wirkus@mwirkus-lap-u:test$ 
```

Passing the command line argument `-std=c++11` to `castxml` as done in this PR seems to help. But
* I don't know about possible implications of this
* There might be objections with enabling c++11 per default

Please review and give comments how to go on with this.

### CODE REVIEW

**Comment by doudou** [comment]
Which cflags should be enabled is not the job's of typelib, but of typelib's caller (i.e. this is the wrong place to do that)

I see two things that need to be fixed with respect to this:
 - packages that export C++11 headers should have `-std=cxx11` in the `Cflags:` of their pkg-config file (likely to be a change in `base/cmake`), and we must make sure that the flag is propagated by orogen to the typelib parser (may work as-is, I honestly don't know)
 - add a 'cxxstd' statement to the orogen file that would tell orogen to build the package as C++11 (needed if one wants to either use C++11 in the orogen package's headers and/or privately in the tasks). The tricky part here is that it must cause the corresponding flags to be given to typelib *and* in the orogen-generated pkg-config files.

**Comment by maltewi** [comment]
Hi,

thanks for the reply and sorry for the delay.

Let's have a look at your first point.

> packages that export C++11 headers should have -std=cxx11 in the Cflags: of their pkg-config file (likely to be a change in base/cmake), and we must make sure that the flag is propagated by orogen to the typelib parser (may work as-is, I honestly don't know)

I think [this is the place where orogen calls typelib](https://github.com/orocos-toolchain/orogen/blob/master/lib/orogen/gen/typekit.rb#L1523). When inspecting the `options` argument here:
```ruby
{:opaques_ignore=>true,
 :merge=>false,
 :required_files=>
  ["/media/wirkus/Data/development/d-rock/install/include/my_test_package/bla/MyHeader.hpp"],
 :opaques=>[],
 :include_paths=>
  ["/media/wirkus/Data/development/d-rock/install/include/my_test_package",
    "/media/wirkus/Data/development/d-rock/install/include",
   "/media/wirkus/Data/development/d-rock/install/include/rtt/mqueue",
   "/media/wirkus/Data/development/d-rock/install/include/rtt/transports/corba",
   "/usr/include/eigen3",
   "/media/wirkus/Data/development/d-rock/install/include/",
   "/media/wirkus/Data/development/d-rock/install/include/orocos",
   "/media/wirkus/Data/development/d-rock/install/include/orocos/std/types",
   "/media/wirkus/Data/development/d-rock/install/include/orocos/base/types",
   "/media/wirkus/Data/development/d-rock/install/include/orocos/logger/types"],
 :define=>["OROCOS_TARGET=gnulinux", "__orogen2"]}
```
Does not contain any hint of c++11 inside the options.

These properties are then passed around in typelib a bit to finally end up in the place, [where my PR hardcoded the `-std=c++11`-flag](https://github.com/orocos-toolchain/typelib/blob/master/bindings/ruby/lib/typelib/gccxml.rb#L935). This is how the code looks like:
```ruby
        def self.castxml(file, options)
            cmdline = [castxml_binary_name, *castxml_default_options, "--castxml-gccxml", '-x', 'c++']
            required_files = (options[:required_files] || [file])
            if raw = options[:rawflags]
                cmdline.concat(raw)
            end

            if defs = options[:define]
                defs.each do |str|
                    cmdline << "-D#{str}"
                end
end
```

So from the typelib-side, a solution might be to add something like
```
            if cflags = options[:cflags]
                cmdline.concat(cflags)
            end
```
to [gccxml.rb](https://github.com/orocos-toolchain/typelib/blob/master/bindings/ruby/lib/typelib/gccxml.rb#L935).

---

Now let's look at the orogen side and go back to I think [perform_pending_loads in orogen/gen/typekit.rb](https://github.com/orocos-toolchain/orogen/blob/master/lib/orogen/gen/typekit.rb#L1523). If I understood correctly, the question now is: "How do we determine which CFlags are required for handling the header given header files?". Part of the answer is pkg-config and the `OroGen::Gen::RTT_CPP::Typekit::used_libraries` instance variable, an array containing the pkg-config data for the included libraries. E.g. introspecting `self.used_libraries[2].cflags` returns exactly, what we need:
```
pry(#<OroGen::Gen::RTT_CPP::Typekit>)> self.used_libraries[2].cflags
=> "-std=cxx11 -I/media/wirkus/Data/development/d-rock/install/include"
```

At which point in the source code should we relate the CFlags to the header file? My suggestion is directly, when loading the header files at [OroGen::Gen::RTT_CPP::Typekit#load](https://github.com/orocos-toolchain/orogen/blob/master/lib/orogen/gen/typekit.rb#L1180). If the flag ends up in the pending_load_options, it will be eventually passed to typelib.

Now another question arises: How do we know which CFlags are required for which Header file? We would need to find out, that the given file, e.g. `"/media/wirkus/Data/development/d-rock/install/include/bla/MyHeader.hpp"` originates from a package called my_test_package. This might not be possible...
So, final question: What do you think, would it be okay to pass a merged version of all cflags to all headers, like:
```ruby
         user_options[:cflags] = self.used_libraries.map do |ul| ul.cflags.split end.flatten.uniq
```
in [OroGen::Gen::RTT_CPP::Typekit#load](https://github.com/orocos-toolchain/orogen/blob/master/lib/orogen/gen/typekit.rb#L1215).

**Comment by doudou** [comment]
:+1: Thanks for the thorough analysis.

FYI, I've done some work to ensure that the Rock CMake macros export `-std=c++XX` in the pkg-config file when targets use C++XX. So, [that should be fine now](https://github.com/rock-core/base-cmake/pull/43).

On the typelib side, `:rawflags` already has the role of `:cflags` (it basically contains flags that should be passed as-is to the command line), so no need to change anything there IMO - even if the name is less than optimal, I don't believe it's worth changing.

On the orogen side, `#raw_cflags` returns the cflags as an array while `#cflags` just returns a string. `#cflags` is the way it is for historical reasons (I did not want to break backward compatibility when I introduced `#raw_cflags`). The array version is better since it requires no quoting.

orogen already guesses the header-to-package mapping. However, this is not required as the assumption is that all packages given to `Typekit#using_library`  should be used for building the typekit. So, the right solution would be to merge cflags and passing them to the import, the way you propose. Note that these changes would fix corner-case bugs where the Cflags change the structure layouts, something we don't take at all into account so far.

So, it seems that it would be enough to concatenate the used librarie's `#raw_cflags` and pass that as a `:rawflags` to the typelib importer.

FYI:

1. The "right" way to split a command line into its constituents it to use the `Shellwords` package which properly handles quoting.

2. If one does **not** want a using_library to be used by the typekit, he/she should declare
    it in the orogen file with:

    ~~~
    using_library 'package', typekit: false
    ~~~

    Which makes `Project#using_library` [**not** forward the call to `#typekit`](https://github.com/orocos-
    toolchain/orogen/blob/master/lib/orogen/gen/project.rb#L852).

**Comment by maltewi** [comment]
@doudou: Please have a look at orocos-toolchain/orogen#95. If it's okay for you close this one here.

**Comment by doudou** [comment]
Superseded by https://github.com/orocos-toolchain/typelib/pull/102

**Pull request closed without merging**
