### PR TITLE
Clang Integration

### PR DESCRIPTION
**Pull request by doudou**
This is the workspace to finalize the Clang importer work. It supersedes #35

### CODE REVIEW

**Comment by doudou** [comment]
@marvin2k: updated according to your comments (and with the bugfix)

**Comment by marvin2k** [comment]
As a sidenote: The OSX guys (@D-Alex and @malter) are eager to use this, since gccxml is broken there(?) The current state is that the LLVM/Clang on macports uses the wrong stdlib...

**Comment by doudou** [comment]
I know, but I'd like to properly make clang optional before we merge it on master

**Comment by marvin2k** [comment]
Yeah sure, I'm the last one who wants this in enabled in master ;-) I just wanted the two to be included in this thread.

**Comment by marvin2k** [comment]
@malter: I think the testcase added in 593a3341018e5a12b7cac5b3b80cc134260a5125 illustrates your problem

**Comment by goldhoorn** [comment]
*pong* okay for merge for all?

**Comment by goldhoorn** [comment]
@marvin2k: can you merge against master, the PR got outdated, sorry

**Comment by doudou** [comment]
Test https://github.com/orocos-toolchain/autoproj/pull/8 before merging this, please

**Comment by goldhoorn** [comment]
Why this PR get closed?, it is still open (i only added a commit)

**Comment by doudou** [comment]
Because you merged it ... You pushed to master

**Comment by goldhoorn** [comment]
I pushed a while ago stuff to my personal ones, as you can see in #54 it's still unmerged (but it can merged now)

**Pull request merged**
