### PR TITLE
made gccxml optional

### PR DESCRIPTION
**Pull request by planthaber**

### CODE REVIEW

**Comment by doudou** [comment]
@smits are you guys still depending on the manifest.xml ?

**Comment by doudou** [comment]
First we would need to check whether the orocos guys still use the manifest.xml, if they do, we can't depend_optional (they don't know about it). My guess is that they do not, but hey.

Then, I would rather remove them from there completely, and add the relevant dependency in https://github.com/orocos-toolchain/autoproj/blob/master/orocos.autobuild#L80. The remove_dependency hack does not work anymore in v2.

**Comment by planthaber** [comment]
Ah, thats why rosdep is still used there.
Should we settle for setting gccxml to ignore then?

**Comment by smits** [comment]
@doudou Not that I know of, @meyerj do know anything still depending on the manifest.xml?

**Comment by meyerj** [comment]
We do not need it and would prefer to have `manifest.xml` removed completely. But if the file exists, it has to follow [ROS' manifest.xml specification](http://docs.ros.org/independent/api/rospkg/html/manifest_xml.html). Unfortunately some tools like [rosdep](http://docs.ros.org/independent/api/rosdep/html/) still prefer `manifest.xml` over `package.xml` even if both files exist and would otherwise complain about format errors.

I quickly checked with this branch in ROS indigo: rosdep runs successfully with the modified `manifest.xml`, but it simply ignores unknown tags like `<depend_optional>` and would not install optional dependencies. I think that's fine. The Python package that is responsible for the parsing is at https://github.com/ros-infrastructure/rospkg.

Whenever dependencies are updated, it is important to update both manifest files as long as we have two, because some other tools ignore `manifest.xml`. The latest specification for the newer `package.xml`  file format is [here](http://www.ros.org/reps/rep-0140.html). In manifest.xml, keys listed with `<rosdep name="foo" />` must be listed in the [rosdep database](https://github.com/ros/rosdistro/tree/master/rosdep) and keys listed with `<depend package="bar" />` must be other ROS packages which are either released or located in the same source space. For `package.xml`, this difference disappeared and each key must be one of both. Unfortunately there is no notion of optional dependencies in either `manifest.xml` or `package.xml`. Ideally we try to keep both databases, rosdep and autoproj, in sync for all used keys.

I have an open PR in rosdistro which also includes the `bundler` key from utilrb: https://github.com/ros/rosdistro/pull/13527

**Comment by doudou** [comment]
> would prefer to have manifest.xml removed completely

I would be OK with moving it to the package set if that helps. The rosdep/depend entries are also considered identical by autoproj right now. From autoproj's point of view, there's no point in switching to the package.xml format, so I really don't plan to implement that.

> The latest specification for the newer package.xml file format is here

We don't use ROS. The best I can do for you there is to create pull requests whenever there are new dependencies showing up to let you update the ROS side. `depend_optional` was created specifically for the purpose of being ignored by ROS.

**Comment by meyerj** [comment]
> We don't use ROS. The best I can do for you there is to create pull requests whenever there are new dependencies showing up to let you update the ROS side.

+1

> depend_optional was created specifically for the purpose of being ignored by ROS.

Okay, it seems to not break rosdep, so fine to merge from my side.

**Comment by planthaber** [comment]
But this will remove the dependency to gccxml for the ros side.

@doudou whould autoproj override this manifest.xml when we add another one without the dependency to the package set?

**Comment by doudou** [comment]
> Okay, it seems to not break rosdep, so fine to merge from my side.

Even though it does not break rosdep, it's going to break your install if gccxml is not installed anymore.

**Comment by doudou** [comment]
> @doudou whould autoproj override this manifest.xml when we add another one without the dependency to the package set?

Not in v1, and not yet in v2 (I'll change v2 to do that, because it makes more sense)

**Comment by meyerj** [comment]
> Even though it does not break rosdep, it's going to break your install if gccxml is not installed anymore.

Okay, so if I understand it correctly `gccxml` is not truly optional, but the semantics is more that one of `{clang,castxml,gccxml}` needs to be installed? In that case rosdep would indeed fail to install all dependencies. But this is a minor issue as long as rosdep does not abort with an error. For releases (and building binary packages), ROS/[bloom](http://wiki.ros.org/bloom) is only looking at the contents of `package.xml` and we can easily patch the manifest or the generated control files, if necessary. Users who build from source must somehow select which of the optional dependencies to install by selecting them manually.

**Comment by doudou** [comment]
OK then. @planthaber could you modify this PR to comment all these lines out (keeping them for documentation) and propose a PR to orocos.toolchain/orocos.autobuild that would depends_on the right dependency (instead of removing the dependency as it does now). That would be a lot cleaner from Rock's point of view.

**Comment by planthaber** [comment]
How can you decide what is the "right dependency?" 
package.depends "castxml" (or clang, gccxml) in the code part that enables castxml?

**Comment by doudou** [comment]
For reference: https://github.com/orocos-toolchain/autoproj/blob/master/orocos.autobuild#L86

> package.depends "castxml" (or clang, gccxml) in the code part that enables castxml?

Basically, yes. (`depends_on` though)

**Comment by planthaber** [comment]
https://github.com/orocos-toolchain/autoproj/pull/25 now adds the dependencies in the package_set, commented that part here out

**Pull request merged**
